# Generated by Django 3.1.4 on 2021-01-02 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210102_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='posts',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
