# Generated by Django 3.1.4 on 2021-01-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210102_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
