# Generated by Django 3.1.4 on 2021-01-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
